// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/store-tile/CompactChip.tsx": () => import("../components/mockups/store-tile/CompactChip.tsx"),
  "./components/mockups/store-tile/GradientOverlay.tsx": () => import("../components/mockups/store-tile/GradientOverlay.tsx"),
  "./components/mockups/store-tile/MagazineCard.tsx": () => import("../components/mockups/store-tile/MagazineCard.tsx")
};
